name: Build APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install system packages
      run: |
        sudo apt update
        sudo apt install -y git zip unzip openjdk-17-jdk pkg-config \
                            libgl1-mesa-dev libgles2-mesa-dev python3-pip \
                            python3-setuptools python3-wheel python3-dev \
                            build-essential libffi-dev libssl-dev

    - name: Install Buildozer & Cython
      run: pip install buildozer cython

    - name: Install Android command-line tools (SDK)
      run: |
        export SDKROOT=$HOME/android-sdk
        mkdir -p $SDKROOT/cmdline-tools
        wget https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip -O tools.zip
        unzip tools.zip -d $SDKROOT/cmdline-tools
        mv $SDKROOT/cmdline-tools/cmdline-tools $SDKROOT/cmdline-tools/latest
        yes | $SDKROOT/cmdline-tools/latest/bin/sdkmanager \
              --sdk_root=$SDKROOT \
              "platform-tools" \
              "platforms;android-33" \
              "build-tools;33.0.2"

    - name: Fix symlinks and paths for Buildozer
      run: |
        export SDKROOT=$HOME/android-sdk
        export ANDROID_SDK_ROOT=$SDKROOT
        
        # Create expected symlinks
        mkdir -p $SDKROOT/tools/bin
        ln -s $SDKROOT/cmdline-tools/latest/bin/* $SDKROOT/tools/bin/

        # Expose to PATH
        echo "$SDKROOT/tools/bin" >> $GITHUB_PATH
        echo "$SDKROOT/platform-tools" >> $GITHUB_PATH
        echo "ANDROID_SDK_ROOT=$SDKROOT" >> $GITHUB_ENV

    - name: Build APK
      run: buildozer android debug

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: FaceApp-APK
        path: bin/*.apk
