name: Build APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install build dependencies
        run: |
          sudo apt update
          sudo apt install -y git zip unzip openjdk-17-jdk \
            pkg-config libgl1-mesa-dev libgles2-mesa-dev \
            python3-pip python3-setuptools python3-wheel python3-dev \
            build-essential libffi-dev libssl-dev

      - name: Install Buildozer
        run: pip install buildozer cython

      - name: Build APK
        run: buildozer android debug

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: FaceApp-APK
          path: bin/*.apk
