
name: Build APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install all required packages and dev tools
      run: |
        sudo apt-get update
        sudo apt-get install -y git zip unzip openjdk-17-jdk pkg-config           build-essential autoconf automake libtool libltdl-dev           libffi-dev libssl-dev cmake m4           python3-pip python3-setuptools python3-wheel python3-dev           libgl1-mesa-dev libgles2-mesa-dev libsqlite3-dev

        # Fix for autoreconf macro errors
        libtoolize --install

    - name: Install Buildozer and dependencies
      run: |
        pip install --upgrade pip
        pip install buildozer cython

    - name: Install Android SDK and NDK
      run: |
        export ANDROID_HOME=$HOME/.buildozer/android/platform/android-sdk
        mkdir -p $ANDROID_HOME/cmdline-tools
        wget https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip -O tools.zip
        unzip tools.zip -d $ANDROID_HOME/cmdline-tools
        mv $ANDROID_HOME/cmdline-tools/cmdline-tools $ANDROID_HOME/cmdline-tools/latest

        yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager           --sdk_root=$ANDROID_HOME           "platform-tools"           "platforms;android-33"           "build-tools;33.0.2"           "ndk;25.2.9519653"

    - name: Fix Buildozer paths and environment
      run: |
        export ANDROID_HOME=$HOME/.buildozer/android/platform/android-sdk
        mkdir -p $ANDROID_HOME/tools/bin
        ln -sf $ANDROID_HOME/cmdline-tools/latest/bin/* $ANDROID_HOME/tools/bin/

        echo "ANDROID_SDK_ROOT=$ANDROID_HOME" >> $GITHUB_ENV
        echo "$ANDROID_HOME/build-tools/33.0.2" >> $GITHUB_PATH
        echo "$ANDROID_HOME/platform-tools" >> $GITHUB_PATH
        echo "$ANDROID_HOME/tools/bin" >> $GITHUB_PATH

    - name: Build APK
      run: buildozer android debug

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: FaceApp-APK
        path: bin/*.apk
