name: Build APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y git zip unzip openjdk-17-jdk pkg-config \
          libgl1-mesa-dev libgles2-mesa-dev python3-pip \
          python3-setuptools python3-wheel python3-dev \
          build-essential libffi-dev libssl-dev \
          autoconf automake libtool  # ✅ Fixes autoreconf build errors

    - name: Install Buildozer & Cython
      run: pip install --upgrade pip && pip install buildozer cython

    - name: Download & Install Android SDK + NDK
      run: |
        export SDK_ROOT=$HOME/.buildozer/android/platform/android-sdk
        mkdir -p $SDK_ROOT/cmdline-tools
        wget https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip -O tools.zip
        unzip tools.zip -d $SDK_ROOT/cmdline-tools
        mv $SDK_ROOT/cmdline-tools/cmdline-tools $SDK_ROOT/cmdline-tools/latest

        yes | $SDK_ROOT/cmdline-tools/latest/bin/sdkmanager --sdk_root=$SDK_ROOT \
          "platform-tools" \
          "platforms;android-33" \
          "build-tools;33.0.2" \
          "ndk;25.2.9519653"

    - name: Fix paths for Buildozer compatibility
      run: |
        export SDK_ROOT=$HOME/.buildozer/android/platform/android-sdk

        # Symlink for sdkmanager (expected at tools/bin/)
        mkdir -p $SDK_ROOT/tools/bin
        ln -sf $SDK_ROOT/cmdline-tools/latest/bin/* $SDK_ROOT/tools/bin/

        # Add to environment
        echo "ANDROID_SDK_ROOT=$SDK_ROOT" >> $GITHUB_ENV
        echo "$SDK_ROOT/build-tools/33.0.2" >> $GITHUB_PATH
        echo "$SDK_ROOT/platform-tools" >> $GITHUB_PATH
        echo "$SDK_ROOT/tools/bin" >> $GITHUB_PATH

    - name: Build APK
      run: buildozer android debug

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: FaceApp-APK
        path: bin/*.apk
